"""empty message

Revision ID: 82e002b9fa03
Revises: ac823d32e777
Create Date: 2020-04-08 11:26:19.839568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e002b9fa03'
down_revision = 'ac823d32e777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('precipitation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'precipitation')
    # ### end Alembic commands ###
